apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: us-east-1
  version: "1.30"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
  - name: final-node-group
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    # commented because it's deprecated, and will be removed later.
    # ssh:
    #   enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/LabRole # we will be using an environment vairable.

