apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final  
data:
  DBHOST: mysql-service        
  DBPORT: "3306"                
  BACKGROUND_IMAGE_URL: ss3://testclo835-abi/IMG_20231115_131651.jpg
  USER_NAME: Abi, Omar, Swagat
