apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80           # Cluster-internal port
      targetPort: 81     # Flask container's internal port
      nodePort: 30000    # Exposed on localhost:30081
