apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
  loadBalancerSourceRanges:
    - 0.0.0.0/0 
