apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: flask-container
          image: 184549016595.dkr.ecr.us-east-1.amazonaws.com/app:v0.1
          ports:
            - containerPort: 81
          env:
            # ConfigMap values
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DBPORT
            - name: BACKGROUND_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: BACKGROUND_IMAGE_URL
            - name: USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: USER_NAME

            # Secret values
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBPWD
