apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: my_app:latest
          # imagePullPolicy: Never  # Since you're using kind-loaded local image
          ports:
            - containerPort: 81   # Must match your app.py Flask port

        imagePullSecrets:
          - name: ecr-secrets

          env:
            # ConfigMap values
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DBPORT
            - name: BACKGROUND_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: BACKGROUND_IMAGE_URL
            - name: USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: USER_NAME

            # Secret values
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBPWD

            # Optional: AWS credentials from secret (if used)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SESSION_TOKEN

